### ISSUE TITLE
Automated mkdocs deployment to gh-pages on new tag

### ISSUE THREAD

**Issue by alexandreleroux** [ECCC-MSC/open-data#23]
Tel que discuté, quand tu seras bloqué sur d'autres tâches, voici une copie de ce ticket interne. Merci :-)

_Objectif : automatiquement mettre à jour le contenu de la doc publique sur GitHub gh-pages après un tag sur GitHub master, si possible_

_J'ai effectué une recherche rapide et ce n'est pas clair pour moi si une solution simple existe présentement. Peux-tu svp valider ? Merci !_

cc @Dukestep @RousseauLambertLP

**Comment by jul31415** [comment]
je vais y jeter un oeil

**Comment by SamGuay** [comment]
Je me suis amusé à voir s'il y avait une façon simple de le faire avec mkdocs et vous pouvez voir le résultat sur ma branche [gh-action](https://github.com/SamGuay/open-data/blob/gh-action/.github/workflows/publish_doc.yaml). 

J'ai pu build le [site](https://samguay.github.io/open-data) sans problème, si vous voulez un aperçu du workflow et des logs, vous pouvez les voir [ici](https://github.com/SamGuay/open-data/runs/2537190958?check_suite_focus=true).

Si vous le voulez, je peux faire une PR avec le nouveau fichier.

**Comment by Dukestep** [comment]
Bonjour (avec un peu de retard!),

Nous implimenterons très bientôt cette fonctionnalité avec un workflow GitHub Actions très similaire!

Le prochain release de la documentation devrait ce faire avec se workflow automatisé! Merci de la suggestion!

**Comment by Dukestep** [comment]
La version `2.6.15` de la doc  a été publiée via un workflow automatisé suite à la création du release! Je ferme donc ce ticket.

**Comment by SamGuay** [comment]
Excellent, heureux d'apprendre la nouvelle!
