### ISSUE TITLE
Arthur's Jupyter Notebook use case

### ISSUE THREAD

**Issue by alexandreleroux** [ECCC-MSC/open-data#24]
Tel que discuté, voici une série de notes internes pour garder trace des éléments à considérer et/ou compléter au sujet du premier "cas d'utilisation" dans la documentation. Le snippet que je compte utiliser pour pointer vers ce use case dans la doc et dans l'annonce est celui-ci : "Directly access and query MSC data from an interactive Python script".

Le plus gros questionnement sur lequel nous devons converger est celui-ci ; 

* [x] décider comment on modifie ce cas d'utilisation pour le rendre davantage pertinent à l'année longue. Le [cas d'utilisation initial](http://collaboration.cmc.ec.gc.ca/cmc/cmos/publications/ensemble_weather_forecast_example_f.pdf) implique des températures >25, ce qui est assez rare pour nos latitudes. Parmi les options discutées : utiliser un exemple associé (A) à la précipitation (e.g. amener son parapluie avec soi ou vente de parapluies ?), ou (B) la couverture nuageuse, ou encore (C) un seuil de vent. B et C ont l'avantage de fonctionner également en hiver.

Autrement, voici une première série de commentaires sur [l'ébauche initiale](https://marieevelb.github.io/jupyter-notebook/Arthur/) :

* [ ] intégrer l'ébauche initiale dans le dossier `docs-dev` dans la branche `master` de la doc publique
* [x] ajouter des sections avec `#`, au moins une pour l'intro, une pour le contenu du cas d'utilisation, et une pour la conclusion ?
* [x] rédiger une courte intro qui mettre l'accent sur ce qui sera couvert, soit :    
    * how to access and query weather data from the MSC GeoMet geospatial web services
    * query data for specific values at specific locations
    * temporal queries 
    * show results
* changements suggérés au code : 
    * [x] le code Python déborde de la fenêtre présentée par mkdocs
    * [x] les valeurs pour `interval` et `totaltime` pourrait être récupéré automatiquement du GetCapa avec &layers, et écrasés par l'usager si désiré
    * [x] dans la portion texte, mettre en mode `code` ce qui appartient au code, tel que `bbox` et `#` par exemple
    * [x] portion du territoire => lieu ?
* [x] ajout de graphiques présentant les résultats. Soit matplotlib ou plot.ly. Montrer les variables météo dans le temps ainsi que les variables associées au use case ($, # d'employés). Dans un graphique si lisible, sinon deux ?
* [x] identifier le meilleur endroit pour héberger le Notebook de manière interactive. mybinder.org ? Si un compte est nécessaire, nous le nommerons `eccc-msc` et je suggère que @Dukestep soit en charge du compte 
* [x] révision du code Python par @RousseauLambertLP et @Dukestep , considérer Flake8 ?
* [x] traduire le cas d'utilisation
* [x] inviter Miguel et Sandrine à réviser le cas d'utilisation renouvellé
* [ ] une fois geomet-weather 2.10 disponible, utiliser la réponse GFI en JSON au lieu d'ASCII
* [ ] une fois geomet-weather 2.12 disponible, utiliser les données du GEPS au lieu du REPS

Merci !

**Comment by marieevelb** [comment]
Je ne peux toujours pas cocher les éléments de la liste.

**Comment by edouardsandrine** [comment]
Détail éditorial : je remplacerais prédiction par... prévision !

**Comment by marieevelb** [comment]
> Détail éditorial : je remplacerais prédiction par... prévision !

Bon point! J'ai fait les modifications.

**Comment by alexandreleroux** [comment]
C'est publié maintenant, merci @marieevelb ! 

Je garde le ticket ouvert pour les modifs suivantes qui risquent d'être effectués au cours de juillet ?
* une fois geomet-weather 2.10 disponible, utiliser la réponse GFI en JSON au lieu d'ASCII
* une fois geomet-weather 2.12 disponible, utiliser les données du GEPS au lieu du REPS

**Comment by alexandreleroux** [comment]
Le GFI est en JSON maintenant et le choix du REPS est adéquat. Je ferme ce vieux ticket, merci !
