### ISSUE TITLE
API open-data/msc-datamart/ missing city pages

### ISSUE THREAD

**Issue by radzhome** [ECCC-MSC/open-data#30]
So these cities appear in the siteMap but do not have an actual page - 

[['BC', 's0000846'], ['BC', 's0000847'], ['BC', 's0000849'], ['BC', 's0000850'], ['BC', 's0000851'], ['BC', 's0000852'], ['BC', 's0000853'], ['BC', 's0000854'], ['BC', 's0000856'], ['BC', 's0000867'], ['BC', 's0000868']]

So here  for example - https://dd.weather.gc.ca/citypage_weather/xml/siteList.xml

You will notice the record is there

```
<site code="s0000846">
<nameEn>Coquihalla Highway - Hope to Merritt</nameEn>
<nameFr>route de Coquihalla - de Hope à Merritt</nameFr>
<provinceCode>BC</provinceCode>
</site>
```

but pages
https://dd.weather.gc.ca/citypage_weather/xml/BC/s0000846_e.xml
https://dd.weather.gc.ca/citypage_weather/xml/BC/s0000846_f.xml

are missing .. the page just before it 845 is there so url pattern seems right -

https://dd.weather.gc.ca/citypage_weather/xml/BC/s0000845_f.xml

**Comment by edouardsandrine** [comment]
Thanks for your message.

The high elevation forecasts, (the citypage you mentioned above) for seasonal text bulletin forecasts issued only for British Columbia, are available at the following address :

https://dd.weather.gc.ca/citypage_weather/xml/HEF

See the list:

https://dd.meteo.gc.ca/citypage_weather/docs/site_list_towns_en.csv

Hope it helps

Ref: https://eccc-msc.github.io/open-data/msc-data/citypage-weather/readme_citypageweather-datamart_en/

**Comment by radzhome** [comment]
it does. Thanks! Is there any way to indicate to use HEF for these on the siteList page? If you parse the provinceCode you will not get to HEF ever. Maybe another data point is required here?

**Comment by edouardsandrine** [comment]
This will be fixed in a next release, somewhere in spring 2023...

**Comment by edouardsandrine** [comment]
This has been fixed, for example:

```
 <site code="s0000846">
 <nameEn>Coquihalla Highway - Hope to Merritt</nameEn>
 <nameFr>route de Coquihalla - de Hope à Merritt</nameFr>
 <provinceCode>HEF</provinceCode>
 </site>
```

I close this issue. 

Thanks a lot for your collaboration.
