### ISSUE TITLE
Add lon and lat to each city in site list

### ISSUE THREAD

**Issue by radzhome** [ECCC-MSC/open-data#31]
https://dd.weather.gc.ca/citypage_weather/xml/siteList.xml

this page only has the city name /province but would you be able to include the lon/lat? This would help so dont have to pull each weather city page for the lon/lat.

Also seems the lon/lat is not that precise, would be possible to expose more decimals?

**Comment by edouardsandrine** [comment]
You will find this information here:

https://dd.meteo.gc.ca/citypage_weather/docs/site_list_towns_en.csv

See also, the GeoJSON list: https://collaboration.cmc.ec.gc.ca/cmc/cmos/public_doc/msc-data/citypage-weather/site_list_en.geojson

Hope it helps

**Comment by radzhome** [comment]
This is great thanks for sharing but is there any reason why NOT to include that on siteList.xml (the two additional data points)?

**Comment by edouardsandrine** [comment]
Good question, I will investigate if we still need several stations lists and come back to you ...Thanks for your patience.

**Comment by edouardsandrine** [comment]
In the context of the MSC transformation, no more work will be done on citypage_weather, see the announcement:

https://comm.collab.science.gc.ca/mailman3/hyperkitty/list/dd_info@comm.collab.science.gc.ca/thread/Y2ZHPENXK56H3TW43D3SITOACJZVWXGA/

Thanks for your interest in our data and services.

I close this issue.
