### ISSUE TITLE
Duplication in city forcasts

### ISSUE THREAD

**Issue by radzhome** [ECCC-MSC/open-data#32]
I realized that for ottawa there are two unique city codes (weather locations):

```
    ['Ottawa', 'ON', 's0000430'],  # s0000623, s0000430 both are Ottawa - could split up
    ['Ottawa2', 'ON', 's0000623'],  # both use the airport as the weather station and thus have same forecast
```

Any reason why this is broken into two locations? the forecast is the same since it indicates indeed it comes from the same weather station.

Could this not be merged into a single location i.e.
Ottawa (Richmond - Metcalfe - Kanata - Orléans )  ?

Breaking up into north and south not sure if it makes any sense if the data is same as it uses the same weather station.

**Comment by edouardsandrine** [comment]
You are right... It's just for "human" consumption.. not the best answer I agree ! There's a couple other double city pages too. Sudbury and Greater Sudbury are the same page, just some people call it Sudbury and some insist it is Greater Sudbury. When we move to the 10k locations the WeatherCAN app currently uses, hopefully most of these duplicates you see on the web site will be removed and the Natural Resources Canada "Official" location name will be used.

**Comment by edouardsandrine** [comment]
See the last announcement regarding citypage :

https://comm.collab.science.gc.ca/mailman3/hyperkitty/list/dd_info@comm.collab.science.gc.ca/thread/Y2ZHPENXK56H3TW43D3SITOACJZVWXGA/

These new locations will not be added to the XML product on MSC Datamart, but new product will be available in the next years. In the meantime, other sources are available. See the details in the announcement.

Thanks for your interest in our data and services.

I close this issue.
